export const SET_POSTS = 'SET_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const SET_SELECTED_POST = 'SET_SELECTED_POST';
export const SET_SELECTED_POST_COMMENTS = 'SET_SELECTED_POST_COMMENTS';
