export const SET_POSTS = 'SET_POSTS';
export const SET_POSTS_SUCCEED = 'SET_POSTS_SUCCEED';
export const SET_POSTS_FAILED = 'SET_POSTS_FAILED';
export const CREATE_POST = 'CREATE_POST';
export const SET_SELECTED_POST = 'SET_SELECTED_POST';
export const SET_SELECTED_POST_COMMENTS = 'SET_SELECTED_POST_COMMENTS';
