export const SET_TODOS = 'SET_TODOS';
export const CREATE_TODO = 'CREATE_TODO';
export const SET_DETAILED_TODO = 'SET_DETAILED_TODO';
export const SET_DETAILED_TODO_COMMENTS = 'SET_DETAILED_TODO_COMMENTS';
